spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_app
    username: postgres
    password: postgres

    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  resources:
    add-mappings: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false